lab_04/urls.py
from django.urls import path
from . import views

app_name = 'lab_04'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('track-record', views.track_record, name='track-record'),
    path('contact', views.contact, name='contact'),
    path('register-now', views.register_now, name='register-now'),
]

lab_05/urls.py
from django.urls import path
from . import views

app_name = 'lab_05'

urlpatterns = [
    path('', views.index, name='list'),
    path('new', views.createActivityPage, name='createJadwal'),
    path('delete', views.delete_all, name='deleteJadwal'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab_04/', include("lab_04.urls")),
    path('list/', include("lab_05.urls")),
    path('', include("lab_04.urls")),
]

lab_04/models.py
from django.db import models

# Create your models here.

lab_05/models.py
from django.db import models
import calendar

# Create your models here.
class ActivityCategory(models.Model):
    CATEGORY_CLASS = 'Class'
    CATEGORY_QUIZ = 'Quiz'
    CATEGORY_LAB = 'Lab'
    CATEGORY_TEST = 'Test'
    CATEGORY_MEETING = 'Meeting'
    CATEGORY_PLAY = 'Play'
    CHOICES = (
        (CATEGORY_CLASS, 'Class'),
        (CATEGORY_QUIZ, 'Quiz'),
        (CATEGORY_LAB, 'Lab'),
        (CATEGORY_LAB, 'Test'),
        (CATEGORY_LAB, 'Meeting'),
        (CATEGORY_LAB, 'Play'),
    )
    name = models.CharField(max_length=200, choices=CHOICES, default=CATEGORY_CLASS)

class Activity(models.Model):
    name = models.CharField(max_length=200)
    venue = models.CharField(max_length=200)
    time = models.DateTimeField()
    category = models.ForeignKey(ActivityCategory, on_delete=models.CASCADE)

    def day(self):
        return calendar.day_name[self.time.weekday()]

lab_05/forms.py
from django import forms
from .models import ActivityCategory

class ActivityForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Activity Name',
        'required': True,
    }))
    venue = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Venue',
        'required': True,
    }))
    time = forms.DateTimeField(widget=forms.DateTimeInput(format='%d/%m/%Y %H:%M:%S', attrs={
        'class': 'form-control',
        'placeholder': 'MM/dd/YY HH:mm:ss',
        'required': True,
    }))
    category = forms.ChoiceField(choices=ActivityCategory.CHOICES, widget=forms.Select(attrs={
        'class': 'form-control',
        'placeholder': 'Category',
        'required': True,
    }))

lab_04/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def track_record(request):
    return render(request, 'track_record.html')

def contact(request):
    return render(request, 'contact.html')

def register_now(request):
    return render(request, 'register_now.html')

lab_05/views.py
from django.shortcuts import render, redirect
from .models import Activity, ActivityCategory
from .forms import ActivityForm

def index(request):
    activities = Activity.objects.all().order_by('-time')
    return render(request, 'jadwal.html', {'activities': activities})

def createActivityPage(request):
    if request.method == 'POST':
        form = ActivityForm(request.POST)
        if form.is_valid():
            activity = Activity()
            activity.name = form.cleaned_data['name']
            activity.venue = form.cleaned_data['venue']
            activity.time = form.cleaned_data['time']
            category = ActivityCategory(name=form.cleaned_data['category'])
            category.save()
            activity.category = category
            activity.save()

        return redirect('/list')
    else:
        form = ActivityForm()
        return render(request, 'create.html', {'form': form})

def delete_all(request):
    Activity.objects.all().delete()
    ActivityCategory.objects.all().delete()
    return redirect('/list')

lab_04/templates/about.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <title>About</title>
        {% include "head_link.html" %}
    </head>
    <body>
        <!-- width 75% dari, mx(margin x) auto -->
        {% include "navbar.html" %}
        <div class="artcl">
            <h1 style="margin-top:80px">ESTJ-T : The Executive</h1>
            <h1 style="margin-top:100px">I am well known for being an extrovert person</h1>
            <h1>I observe well in many situations</h1>
            <h1>I take decisions carefully</h1>
        </div>
        {% include "socmed.html" %}
    </body>
</html>

lab_04/templates/contact.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <title>Contact</title>
        {% include "head_link.html" %}
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="contact-detail">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <img src="https://i.imgur.com/7fypjob.png" alt="Call" style="width:200px; height:200px">
                        <h2>+62 813 1676 3649</h2>
                    </div>
                    <div class="col">
                        <img src="https://i.imgur.com/HUyjcrs.png" alt="Email" style="width:200px; height:200px">
                        <h2>samuel.dimas@rocketmail.com</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="contact-caption">
            <div class="d flex justify-content-around">
                <h2>You can contact me through one of these media above</h2>
                <h2>OR</h1>
                <h2>You can surf to one of my social media accounts below</h2>
            </div>
        </div>
        <div id="socmed-contact">
            {% include "socmed.html" %}
        </div>
    </body>
</html>

lab_04/templates/head_link.html
{% load static from staticfiles %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">
<link rel="shortcut icon" href="{% static 'icon.png' %}">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

lab_04/templates/home.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <title>Home</title>
        {% include "head_link.html" %}
    </head>
    <body>
        {% include "navbar.html" %}     
        <div>
            <span class="circle">
                <h2 style="margin-top: 28px">SD</h2>
            </span>
        </div>
        <div class="artcl">
            <h1>Welcome to the home of a</h1>
            <h1>PASSIONATE WEB PROGRAMMER</h1>
            <h1>Maintaining the satisfaction of you, users, is my number one priority!</h1>
        </div>
        {% include "socmed.html" %}
    </body>
</html>

lab_04/templates/navbar.html
<header class="sticky-top">
    <nav class="navbar navbar-expand-lg navbar-dark dark-grey-bg">
        <a class="navbar-brand" href="{% url 'lab_04:home' %}"><span class="brand hnl-red-text">Home</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link bold" href="{% url 'lab_04:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link bold" href="{% url 'lab_04:about' %}"><span class="active-ref light-grey-text">About</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link bold" href="{% url 'lab_04:track-record' %}"><span class="active-ref light-grey-text">Track Record</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link bold" href="{% url 'lab_04:contact' %}"><span class="active-ref light-grey-text">Contact</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link bold" href="{% url 'lab_04:register-now' %}"><span class="active-ref light-grey-text">Register Now</span></a>
                </li>
            </ul>
        </div>
    </nav>
</header>
    

lab_04/templates/register_now.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <title>Register Now</title>
        {% include "head_link.html" %}
    </head>
    <body>
        {% include "navbar.html" %}
        <div id="register-caption">
            <h2>Register now to receive new updates about me!</h2>
        </div>
        <div class="container">
            <form>
                <div class="form-group row">
                  <label for="inputName" class="col-sm-2 col-form-label">Name</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="inputName" placeholder="Name">
                  </div>
                </div>
                <div class="form-group row">
                    <label for="inputName" class="col-sm-2 col-form-label">Birthdate</label>
                    <div class="col-sm-10">
                      <input type="date" class="form-control" id="inputDate" placeholder="mm/dd/yyyy">
                    </div>
                  </div>
                <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-10">
                      <input type="email" class="form-control" id="inputEmail3" placeholder="name@youremail.com">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputUserName" class="col-sm-2 col-form-label">Username</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" id="inputUserName" placeholder="Username">
                    </div>
                  </div>
                <div class="form-group row">
                  <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
                  <div class="col-sm-10">
                    <input type="password" class="form-control" id="inputPassword" placeholder="Password">
                  </div>
                </div>
                <div class="form-group row">
                    <label for="inputPasswordConf" class="col-sm-2 col-form-label">Password confirmation</label>
                    <div class="col-sm-10">
                      <input type="password" class="form-control" id="inputPasswordConf" placeholder="Password confirmation">
                    </div>
                  </div>
                <div class="form-group row">
                  <div class="col-sm-2">Checkbox</div>
                  <div class="col-sm-10">
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" id="gridCheck1">
                      <label class="form-check-label" for="gridCheck1">
                        I agree to the terms and condition of this website
                      </label>
                    </div>
                  </div>
                </div>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Register
                </button>
                <div class="button-modal">
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Registration success!</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Thank you for registering to my website!
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
              </form>
            </div>
            {% include "socmed.html" %}
    </body>
</html>

lab_04/templates/socmed.html
<div class="d-flex justify-content-around w-25 mx-auto" style="margin-top:20px">
    <a href="https://www.facebook.com/samueldimassiahaan">
        <img src="https://i.imgur.com/zuLwINs.png" alt="Facebook" style="width: 50px;">
    </a>
    <a href="https://twitter.com/SamuelDimas">
        <img src="https://i.imgur.com/EX57tGU.png" alt="Twitter" style="width: 50px;">
    </a>
    <a href="https://www.instagram.com/_samueldimas/">
        <img src="https://i.imgur.com/KR0xvG6.png" alt="Instagram" style="width: 50px;">
    </a>
    <a href="https://www.linkedin.com/in/samueldimas">
        <img src="https://i.imgur.com/PYa4Am7.png" alt="LinkedIn" style="width: 50px;">
    </a>
    <a href="https://www.youtube.com/channel/UC-Xhb8kAoPddVNCTZfsAEWQ?view_as=subscriber">
        <img src="https://i.imgur.com/M3xY0Nz.png" alt="Youtube" style="width: 50px;">
    </a>
</div>

lab_04/templates/track_record.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <title>Track Record</title>
        {% include "head_link.html" %}
    </head>
    <body>
        <!-- width 75% dari, mx(margin x) auto -->
        {% include "navbar.html" %}
        <div id="record-logo">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <a href="http://pmb.cs.ui.ac.id/">
                            <img src="https://i.imgur.com/Xk9TYm1.png" alt="PMB" style="width: 400px;">
                        </a>
                    </div>
                    <div class="col">
                        <a href="https://bem.cs.ui.ac.id/">
                            <img src="https://i.imgur.com/Enza5SR.png" alt="BEM" style="width: 300px;">
                        </a>
                    </div>
                    <div class="col" style="margin-top:40px; margin-left: 50px">
                        <a href="https://www.instagram.com/pemiracsui/">
                            <img src="https://i.imgur.com/6bSMXGT.png" alt="Pemira" style="width: 300px;">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div id="record-caption">
            <h1>These are my activities this year</h1>
        </div>
        {% include "socmed.html" %}
    </body>
</html>

lab_05/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <title>Schedule</title>
        {% include 'components/head.html' %}
    </head>
    <body>
        {% block content %} {% endblock %}
    </body>
</html>

lab_05/templates/components/head.html
{% load static from staticfiles %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">
<link rel="shortcut icon" href="{% static 'icon.png' %}">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

lab_05/templates/create.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block content %}


<div class="form-page">
    <div class="container">
        <h2>Enter your new activity</h2>
        <br>
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.name }}" style="color:white;">{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
            <br>
            <input type="submit" class="btn btn-dark" value="Create">
        </form>
    </div>
</div>

{% endblock %}

lab_05/templates/jadwal.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block content %}

<div class="container">
    <div class="btn-delete">
        <a href="{% url 'lab_05:createJadwal' %}" class="btn btn-dark">Create new Activity</a>
        <a class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">Delete all</a>
    </div> 
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Prompt window</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                         <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% if activities %}
                <div class="modal-body">
                    Are you sure to delete all activities you created?
                </div>
                <div class="modal-footer">
                    <div class="btn-delete">
                        <a class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <a href="{% url 'lab_05:deleteJadwal' %}" class="btn btn-danger">Delete all</a>
                    </div>
                </div>
                {% else %}
                <div class="modal-body">
                    You have no activities now.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% if activities %}
{% for activity in activities %}
<div class="container">
    <div class="cont-list">
        <h2>{{ activity.name }}</h2>
        <p>{{ activity.day }}, {{ activity.time }} at {{ activity.venue }}</p>
        <p>Category: {{ activity.category.name }}</p>
    </div>
</div>
{% endfor %}

{% else %}
<div class="box">
    <div class="form-page-no-activities">
        <p>No activities!</p>
    </div>
</div>
{% endif %}

{% endblock %}